### ISSUE TITLE
Service is unavailable

### ISSUE THREAD

**Issue by mamitry** [abanobmikaeel/coptic.io#19]
Hi Abanoub,

Registration on [coptic.io](http://coptic.io/) is not possible. The page is down.
The same applies to the API Documentation [api.coptic.io/docs](http://api.coptic.io/docs) and to https://coptic-calendar-api.herokuapp.com/.
Any plan to bring this up again?

Thx
Martin

**Comment by abanobmikaeel** [comment]
Hi! So I've been trying to deploy it on AWS Lambda but have been very busy! Will work on that this week hopefully!

**Comment by abanobmikaeel** [comment]
App is now deployed on coptic.io @mamitry going to add logic for API tokens soon, but for now feel free to hit the API directly, also gonna update docs soon God willing!
